apiVersion: v1
kind: Service
metadata:
  name: kafka-rest-proxy
  namespace: kafka-gustavo
spec:
  ports:
  - port: 8082
    name: kafka-rest-proxy
  selector:
    app: kafka-rest-proxy
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka-rest-proxy
  namespace: kafka-gustavo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-rest-proxy
    spec:
      containers:
      - name: kafka-rest-proxy
        image: confluentinc/cp-kafka-rest:3.3.0
        command:
        - sh
        - -c
        - 'export KAFKA_REST_LISTENERS="http://$KAFKA_REST_HOST_NAME:8082"
           && /etc/confluent/docker/run'
        env:
        - name: KAFKA_REST_ZOOKEEPER_CONNECT
          value: "zookeeper:2181/kafka"
        - name: KAFKA_REST_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_REST_SCHEMA_REGISTRY_URL
          value: "http://kafka-schema-registry:8081"
        ports:
        - containerPort: 8082
          name: rest-port
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
