apiVersion: v1
kind: Service
metadata:
  name: kafka-schema-registry
  namespace: kafka-gustavo
spec:
  ports:
  - port: 8081
    name: kafka-schema-registry
  selector:
    app: kafka-schema-registry
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka-schema-registry
  namespace: kafka-gustavo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-schema-registry
    spec:
      containers:
      - name: kafka-schema-registry
        image: confluentinc/cp-schema-registry:3.3.0
        command:
        - sh
        - -c
        - 'export SCHEMA_REGISTRY_LISTENERS="http://$SCHEMA_REGISTRY_HOST_NAME:8081"
           && /etc/confluent/docker/run'
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: "zookeeper:2181/kafka"
        - name: SCHEMA_REGISTRY_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SCHEMA_REGISTRY_SCHEMA_REGISTRY_ZK_NAMESPACE
          value: "kafka/schema_registry"
        ports:
        - containerPort: 8081
          name: schema-port
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
