apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka-gustavo
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  namespace: kafka-gustavo
spec:
  ports:
  - port: 2888
    name: peer
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zookeeper
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zoo
  namespace: kafka-gustavo
spec:
  serviceName: zookeeper-headless
  replicas: 5
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - zookeeper
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 10
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:3.3.0
        # We set ZOOKEEPER_SERVER_ID in a hacky way in command because k8s does
        # not currently makes the index of the pod available. $ZOOKEEPER_SERVERS
        # gets modified so that we replace each replica address with 0.0.0.0
        # since otherwise zookeper complains.
        command:
        - sh
        - -c
        - 'export ZOOKEEPER_SERVER_ID=$(expr $(hostname | grep -o "[[:digit:]]*$") + 1)
           && export ZOOKEEPER_SERVERS=$(echo $ZOOKEEPER_SERVERS | sed "s/zoo-$(expr $(hostname | grep -o "[[:digit:]]*$")).zookeeper-headless/0.0.0.0/")
           && /etc/confluent/docker/run'
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_INIT_LIMIT
          value: "5"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "2"
        - name: ZOOKEEPER_SERVERS
          value: "zoo-0.zookeeper-headless:2888:3888;zoo-1.zookeeper-headless:2888:3888;zoo-2.zookeeper-headless:2888:3888;zoo-3.zookeeper-headless:2888:3888;zoo-4.zookeeper-headless:2888:3888"
        - name: HOSTNAME
          value: "zoo-0.zookeeper-headless"
        ports:
          - containerPort: 2181
            name: client
          - containerPort: 2888
            name: peer
          - containerPort: 3888
            name: leader-election
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        readinessProbe:
          exec:
            command:
            - bin/sh
            - -c
            - '[ "imok" = "$(echo ruok | nc -w 1 127.0.0.1 2181)" ]'
        volumeMounts:
        - name: data
          mountPath: /var/lib/zookeeper/data
      volumes:
      - name: data
        emptyDir: {}
